### Get all customers
GET http://localhost:3000/api/customers



### Add Customer
POST http://localhost:3000/api/customers
Content-Type: application/json

{
    "name": "Kalle",
    "country": "Sweden",
    "age": 19

}


### Edit user information
#Change id to the specific customer

PUT http://localhost:3000/api/customers/1
Content-Type: application/json

{
    "name": "Hej",
    "country": "Norge",
    "age": 18
}


### Delete user
#Change id to the specific customer
DELETE http://localhost:3000/api/customers/1

